version: "3.9"
services:
  db:
    image: postgres:16
    container_name: knu-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: knu_testing
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  piston:
    image: ghcr.io/engineer-man/piston
    container_name: knu-piston
    restart: unless-stopped
    privileged: true
    ports:
      - "2000:2000"
    volumes:
      - piston-packages:/piston/packages

volumes:
  db-data:
  piston-packages:
