import {
  IsArray,
  IsBoolean,
  IsIn,
  IsNotEmpty,
  IsNumber,
  IsOptional,
  IsString,
  ValidateNested,
} from 'class-validator';
import { Type } from 'class-transformer';

/**
 * Simplified shape used for bulk imports (e.g., from a JSON file pasted by a teacher
 * or auto-generated by Claude from a PDF/DOCX document). Each `ImportQuestionItem`
 * is normalized server-side into a `CreateQuestionDto`.
 */
export class ImportOptionDto {
  @IsString()
  @IsNotEmpty()
  value: string;

  @IsBoolean()
  isCorrect: boolean;

  @IsOptional()
  @IsString()
  label?: string;
}

export class ImportMatchingPairDto {
  @IsString()
  @IsNotEmpty()
  left: string;

  @IsString()
  @IsNotEmpty()
  right: string;
}

export class ImportQuestionItemDto {
  @IsString()
  @IsIn(['SINGLE_CHOICE', 'MULTIPLE_CHOICE', 'OPEN_TEXT', 'MATCHING'])
  type: string;

  @IsString()
  @IsNotEmpty()
  text: string;

  @IsOptional()
  @IsNumber()
  weight?: number;

  @IsOptional()
  @IsNumber()
  perQuestionTimeSec?: number;

  // For SINGLE_CHOICE / MULTIPLE_CHOICE
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ImportOptionDto)
  options?: ImportOptionDto[];

  // For OPEN_TEXT
  @IsOptional()
  @IsArray()
  @IsString({ each: true })
  expectedAnswers?: string[];

  @IsOptional()
  @IsString()
  @IsIn(['EXACT', 'CASE_INSENSITIVE', 'CONTAINS', 'REGEX'])
  matchingMode?: string;

  // For MATCHING
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ImportMatchingPairDto)
  pairs?: ImportMatchingPairDto[];
}

export class ImportQuestionsDto {
  @IsString()
  @IsNotEmpty()
  groupId: string;

  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ImportQuestionItemDto)
  questions: ImportQuestionItemDto[];
}
